version: '3.8'
services:
  mon_influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - mon_influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    expose:
      - 8086
    networks:
      - monitoring    

  mon_prometheus_write:
    image: prom/prometheus:latest
    container_name: prometheus
    command: --enable-feature=remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - mon_prometheus_data:/prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # mon_node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: mon_node-exporter
  #   restart: always
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--path.rootfs=/rootfs'
  #     - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
  #     - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
  #   networks:
  #     - monitoring

  mon_cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: mon_cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8089:8080"
    expose:
      - 8080
      - 8089
    networks:
      - monitoring

  mon_grafana:
     image: grafana/grafana:latest
     container_name: mon_grafana
     restart: unless-stopped
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
       - mon_grafana_data:/var/lib/grafana
       - ./grafana/datasources:/etc/grafana/datasources
       - ./grafana/dashboards:/etc/grafana/dashboards
       - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
     environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
     ports:
       - 3006:3000
     expose:
       - 3006
       - 3000
     networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  mon_grafana_data: {}
  mon_prometheus_data: {}
  mon_cadvisor_data: {}
  mon_influxdb_data: {}
