global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'mon_cadvisor:8080' ]
    metrics_path: '/metrics'
  - job_name: 'browserless'
    static_configs:
      - targets: [ 'browserless:3000' ]
    metrics_path: '/prometheus'
    scrape_interval: 1s

