global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'mon_node-exporter:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'mon_cadvisor:8080' ]

  - job_name: 'caddy'
    static_configs:
      - targets: [ 'mon_caddy:3210' ]

  - job_name: 'browserless'
    static_configs:
    - targets: [ 'host.docker.internal:3003' ]    
    metrics_path: '/prometheus'
